export const CREATE_RECIPE = 'CREATE_RECIPE'
export const CREATE_RECIPE_FAIL = 'CREATE_RECIPE_FAIL'
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES'
export const GET_ALL_RECIPES_FAIL = 'GET_ALL_RECIPES_FAIL'
